version: "3.7"
services: 
    backend-golang-server:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes: 
            - ./backend:/backend